rule first {
    strings:
        $a1 = "light"
        $a2 = "form"
        $a3 = "augur"
        $a4 = "cult"
    condition:
        all of them
}

rule second {
    strings:
        $a1 = "31415"
        $a2 = "27182"
        $a3 = "14142"

        $b1 = { C0 FF EE 00 FF }
        $b2 = { AC 1D 1C 00 FF }
        $b3 = { FA CA DE 00 FF }

        $c1 = { DE AD BE EF 3? 3? 3? 3? BA DB AD BA DB AD }
    condition:
        all of them
}

rule third {
    strings:
        $a1 = "NUMBER" xor
        $a2 = "WORD" xor

        $b1 = "-#839"

		$c1 = "Hydrogen"
		$c2 = "Helium"
		$c3 = "Lithium"
		$c4 = "Beryllium"
		$c5 = "Boron"
		$c6 = "Carbon"
		$c7 = "Nitrogen"
		$c8 = "Oxygen"
		$c9 = "Fluorine"
		$c10 = "Neon"
		$c11 = "Sodium"
		$c12 = "Magnesium"
		$c13 = "Aluminium"
		$c14 = "Silicon"
		$c15 = "Phosphorus"
		$c16 = "Sulfur"
		$c17 = "Chlorine"
		$c18 = "Argon"
		$c19 = "Potassium"
		$c20 = "Calcium"
		$c21 = "Scandium"
		$c22 = "Titanium"
		$c23 = "Vanadium"
		$c24 = "Chromium"
		$c25 = "Manganese"
		$c26 = "Iron"
		$c27 = "Cobalt"
		$c28 = "Nickel"
		$c29 = "Copper"
		$c30 = "Zinc"
		$c31 = "Gallium"
		$c32 = "Germanium"
		$c33 = "Arsenic"
		$c34 = "Selenium"
		$c35 = "Bromine"
		$c36 = "Krypton"
		$c37 = "Rubidium"
		$c38 = "Strontium"
		$c39 = "Yttrium"
		$c40 = "Zirconium"
		$c41 = "Niobium"
		$c42 = "Molybdenum"
		$c43 = "Technetium"
		$c44 = "Ruthenium"
		$c45 = "Rhodium"
		$c46 = "Palladium"
		$c47 = "Silver"
		$c48 = "Cadmium"
		$c49 = "Indium"
		$c50 = "Tin"
		$c51 = "Antimony"
		$c52 = "Tellurium"
		$c53 = "Iodine"
		$c54 = "Xenon"
		$c55 = "Caesium"
		$c56 = "Barium"
		$c57 = "Lanthanum"
		$c58 = "Cerium"
		$c59 = "Praseodymium"
		$c60 = "Neodymium"
		$c61 = "Promethium"
		$c62 = "Samarium"
		$c63 = "Europium"
		$c64 = "Gadolinium"
		$c65 = "Terbium"
		$c66 = "Dysprosium"
		$c67 = "Holmium"
		$c68 = "Erbium"
		$c69 = "Thulium"
		$c70 = "Ytterbium"
		$c71 = "Lutetium"
		$c72 = "Hafnium"
		$c73 = "Tantalum"
		$c74 = "Tungsten"
		$c75 = "Rhenium"
		$c76 = "Osmium"
		$c77 = "Iridium"
		$c78 = "Platinum"
		$c79 = "Gold"
		$c80 = "Mercury"
		$c81 = "Thallium"
		$c82 = "Lead"
		$c83 = "Bismuth"
		$c84 = "Polonium"
		$c85 = "Astatine"
		$c86 = "Radon"
		$c87 = "Francium"
		$c88 = "Radium"
		$c89 = "Actinium"
		$c90 = "Thorium"
		$c91 = "Protactinium"
		$c92 = "Uranium"
		$c93 = "Neptunium"
		$c94 = "Plutonium"
		$c95 = "Americium"
		$c96 = "Curium"
		$c97 = "Berkelium"
		$c98 = "Californium"
		$c99 = "Einsteinium"
		$c100 = "Fermium"
		$c101 = "Mendelevium"
		$c102 = "Nobelium"
		$c103 = "Lawrencium"
		$c104 = "Rutherfordium"
		$c105 = "Dubnium"
		$c106 = "Seaborgium"
		$c107 = "Bohrium"
		$c108 = "Hassium"
		$c109 = "Meitnerium"
		$c110 = "Darmstadtium"
		$c111 = "Roentgenium"
		$c112 = "Copernicium"
		$c113 = "Nihonium"
		$c114 = "Flerovium"
		$c115 = "Moscovium"
		$c116 = "Livermorium"
		$c117 = "Tennessine"
		$c118 = "Oganesson"

        $d1 = "strange"
        $d2 = "undereducation"
        $d3 = "lithium"
        $d4 = "harbinger"
        $d5 = "dormant"
        $d6 = "neumatic"
        $d7 = "ringside"
        $d8 = "outdare"
        $d9 = "flump"
        $d10 = "mesomorphic"
        $d11 = "overcharger"
        $d12 = "zoneless"

        $e1 = "deft"
        $e2 = "flop"
        $e3 = "mild"
    condition:
        all of ($a*, $b*) and 1 of ($c*) and 5 of ($d*) and 1 of ($e*)
}